### ISSUE TITLE
subrequest response headers leaking onto main response

### ISSUE THREAD

**Issue by david-batranu** [plone/plone.subrequest#10]
This causes issues when installing products that have a javascript profile since `config,js` gets called in a subrequest and it sets the `application/javascript` response header.

For more info please check https://github.com/plone/Products.CMFPlone/issues/1806

**Comment by gforcada** [comment]
@david-batranu thanks for the report, @jensens claims that it is already fixed with https://github.com/plone/Products.CMFPlone/commit/20a46bcca5ce095d88d2fe6ebccda0bcf9939d50 would you mind to double check it and re-open if it is still an issue?
