### ISSUE TITLE
Broken Mosaic pages after upgrade to 1.8.2

### ISSUE THREAD

**Issue by agitator** [plone/plone.subrequest#14]
Plone 5.1b4 with
plone.tiles = 1.8.2
plone.subrequest = 1.8.2
plone.app.tiles = 3.0.3
plone.app.standardtiles = 2.1.0
plone.app.blocks = 4.0.6
plone.app.drafts = 1.1.1
plone.app.mosaic = 2.0rc5

After pinning mosaic dependencies to newer versions after working with master, some mosaic pages stopped working.
Existing pages for example https://rc.zhref.agitator.com/themen and https://rc.zhref.agitator.com/intern only deliver a snippet of the original page 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" data-layout="./@@page-site-layout">
  <body>
    <div data-panel="content" data-max-columns="4">
      <div class="mosaic-grid-row">
        <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
          <div class="movable removable mosaic-tile mosaic-plone.app.standardtiles.contentlisting-tile">
          <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.contentlisting/a745baae803d4639b4b692090bb59c14"></div>
          </div>
          </div>
          <div class="movable removable mosaic-tile mosaic-IDublinCore-title-tile">
          <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.field?field=IDublinCore-title"></div>
          </div>
          </div>
        </div>
      </div>
      <div class="mosaic-grid-row">
        <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
          <div class="movable removable mosaic-tile mosaic-plone.app.standardtiles.contentlisting-tile">
          <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.contentlisting/05da373e67d0402b982483b196bb1e6a"></div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
```

The problem only appears with the actual web server in place for logged in users and anonymous (setup ist nginx + varnish + haproxy + 4 plone instances). If I test it on one of the instances directly, everything works fine for logged in users and anonymous.

after going back to
plone.tiles = 1.8.2
plone.subrequest = 1.8
plone.app.tiles = 3.0.3
plone.app.standardtiles = 2.1.0
plone.app.blocks = 4.0.6
plone.app.drafts = 1.1.1
plone.app.mosaic = 2.0rc5
everything worked again

as you can see on https://www.zhref.ch/themen and https://www.zhref.ch/intern 

The actual start page http://rc.zhref.agitator.com/ and  https://www.zhref.ch/ didn't have that problem at all - maybe because the were edited more recently?

@awello @datakurre any clues?

**Comment by datakurre** [comment]
@agitator Do you see any plone.subrequest errors in your logs? Would you be able to log, what kind of URLs plone.subrequest creates in those error situations because of https://github.com/plone/plone.subrequest/pull/13 I don't really understand the bug that pull was fixing and its removal of virtual url parts from the subrequest sounds dangerous.

**Comment by agitator** [comment]
That's the traceback...

```
2017-08-16T14:52:24 INFO Zope Ready to handle requests
------
2017-08-16T14:52:50 ERROR plone.subrequest Error handling subrequest to https://rc.zhref.agitator.com/intern/ich-brauche-infos-zu/@@page-site-layout
Traceback (most recent call last):
  File "/home/elk/zhref/eggs/plone.subrequest-1.8.2-py2.7.egg/plone/subrequest/__init__.py", line 145, in subrequest
    traversed = request.traverse(path)
  File "/home/elk/zhref/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 525, in traverse
    return response.notFoundError(URL)
  File "/home/elk/zhref/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/HTTPResponse.py", line 718, in notFoundError
    "<p><b>Resource:</b> %s</p>" % escape(entry))
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Resource not found</strong></p>

  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> https://rc.zhref.agitator.com/ich-brauche-infos-zu</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
------
2017-08-16T14:52:50 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/elk/zhref/eggs/plone.transformchain-1.2.1-py2.7.egg/plone/transformchain/transformer.py", line 49, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/elk/zhref/eggs/plone.app.blocks-4.0.6-py2.7.egg/plone/app/blocks/transform.py", line 122, in transformIterable
    tree = panel.merge(self.request, result.tree)
  File "/home/elk/zhref/eggs/plone.app.blocks-4.0.6-py2.7.egg/plone/app/blocks/panel.py", line 33, in merge
    layoutTree = utils.resolve(layoutHref)
  File "/home/elk/zhref/eggs/plone.app.blocks-4.0.6-py2.7.egg/plone/app/blocks/utils.py", line 73, in resolve
    resolved = resolveResource(url)
  File "/home/elk/zhref/eggs/plone.app.blocks-4.0.6-py2.7.egg/plone/app/blocks/utils.py", line 117, in resolveResource
    raise NotFound(url)
NotFound: https://rc.zhref.agitator.com/intern/ich-brauche-infos-zu/@@page-site-layout

```

**Comment by datakurre** [comment]
@agitator Could you also share headers from a request below that failing page. Eg. by adding a Python script with print context.REQUEST through ZMI and calling that. It should show, what the URL should be and possible allow to deduct how the patch breaks it for tiles by dropping virtual parts.

**Comment by agitator** [comment]
here you go https://rc.zhref.agitator.com/themen/printRequest

**Comment by agitator** [comment]
not to be confused `www.zhref.ch` is the site name

**Comment by thet** [comment]
maybe revert PR #13 ?
I've seen the self-merged PR and thought it was done at the midsummer sprint, wasn't it?

**Comment by datakurre** [comment]
I know nothing about that PR (not done at the sprint nor by participant of that sprint). Revert is OK for me, but it would be nice to ask more details of the issue the author was trying to fix.

**Comment by agitator** [comment]
@awello any more details about your issue(s)?

**Comment by thet** [comment]
I had the same error. Given that the fix of @awello wasn't explained in detail, without tests and he is unresponsive, I will revert it.
@awello if this is still an issue, let's discuss it.

**Comment by thet** [comment]
Reverted: https://github.com/plone/plone.subrequest/commit/a049a4706a076f07da39138ef1fee30f8c0621f7

**Comment by thet** [comment]
By the way, I got this issue with subrequests in virtual hosted environments, but not when accessing the Zope instance unproxied.
